# Phase 3 Real-Data Cleaning

Purpose: transition the statistical baseline from synthetic/pre-data validation to empirical real participant data preparation.

Scope: this notebook preserves the immutable raw workbook, audits the raw schema, reconstructs trial-level randomisation from the submitted JSON payloads, attaches the frozen Phase 3 acoustic features, derives trial-level preferred mixes without breaking ties, and writes canonical real-data cleaning outputs.

No inferential modelling, Bambi/PyMC fitting, statistical comparison, winsorisation, normalisation, or subjective participant exclusion is performed here.

In [1]:
from pathlib import Path
import sys

PROJECT_ROOT = Path.cwd().resolve()
if PROJECT_ROOT.name == "notebooks":
    PROJECT_ROOT = PROJECT_ROOT.parents[1]
elif not (PROJECT_ROOT / "statistical-baseline").exists():
    PROJECT_ROOT = next(path for path in [Path.cwd().resolve(), *Path.cwd().resolve().parents] if (path / "statistical-baseline").exists())

sys.path.insert(0, str(PROJECT_ROOT / "statistical-baseline" / "src"))
from statistical_baseline.real_data_cleaning import OUTPUT_DIR, RAW_SOURCE, run_cleaning

PROJECT_ROOT, RAW_SOURCE, OUTPUT_DIR

(WindowsPath('C:/Users/oscar/Documents/7. QMUL UNIVERSITY/1. Master Program/3. MSc Project/intent2control-dissertation'),
 WindowsPath('C:/Users/oscar/Documents/7. QMUL UNIVERSITY/1. Master Program/3. MSc Project/intent2control-dissertation/statistical-baseline/data/real/raw/listening_preference_responses_33_immutable.xlsx'),
 WindowsPath('C:/Users/oscar/Documents/7. QMUL UNIVERSITY/1. Master Program/3. MSc Project/intent2control-dissertation/statistical-baseline/data/real'))

## Execute Cleaning Pipeline

The cleaning code reads only from the immutable raw workbook stored under `statistical-baseline/data/real/raw/`. All derived tables are regenerated from code.

In [2]:
outputs = run_cleaning()
summary = outputs["summary"]
validation = outputs["validation"]
manifest = outputs["manifest"]
summary

,raw_submissions,raw_columns,unit_of_observation_raw,group_01_submissions,group_02_submissions,complete_participants,incomplete_participants,possible_duplicates,probable_duplicates,manual_review_cases,...,episodes_found,songs_found,stimuli_found,all_randomisation_mappings_reconstructed,participant_song_episode_trials,trials_with_rating_ties,trial_tie_proportion,all_stimuli_mapped_to_features,z_features_from_frozen_phase3_table,final_gate
0,33,40,one row per participant/submission with trial-...,17,16,33,0,0,0,0,...,EDR-1|EDR-2|FM-1,id_like_to_know|in_the_meantime|lead_me|pourin...,20,True,198,16,0.080808,True,True,REAL DATA READY FOR STATISTICAL MODELLING

## Raw-Data Provenance and Final Design

In [3]:
manifest["raw_provenance"], manifest["raw_shape"], manifest["sheet_audit"], manifest["design"]

({'original_filename': 'listening_preference_responses_33.xlsx',
  'stored_path': 'statistical-baseline\\data\\real\\raw\\listening_preference_responses_33_immutable.xlsx',
  'copied_this_run': True,
  'sha256': '5bab388fbf564e0caf5c1ca8a5a722bf8d517e23c018e48375d076e75dba0bdd',
  'bytes': 294316},
 {'rows': 33, 'columns': 40},
 [{'sheet_name': 'listening-study-5mix', 'row_count': 33, 'column_count': 40},
  {'sheet_name': 'Hoja1', 'row_count': 0, 'column_count': 0}],
 {'stimulus_configuration_version': 'five_mix_frontend_v1_2026-08-06',
  'study_version_expected': 'five_mix_frontend_v1_2026-08-06',
  'schema_version_expected': 'five_mix_netlify_forms_v1',
  'group_count': 2,
  'songs_total': 4,
  'stimuli_total': 20,
  'episodes': ['EDR-1', 'EDR-2', 'FM-1'],
  'ratings_per_participant': 30,
  'comments_per_participant': 6,
  'comment_unit': "one comparative comment per participant x song x episode trial, repeated on each of that trial's five rating rows"})

## Raw Schema Audit

In [4]:
outputs["schema_audit"][["column_name", "dtype", "missing_count", "unique_non_missing", "column_role", "json_parse_errors"]]

,column_name,dtype,missing_count,unique_non_missing,column_role,json_parse_errors
0,study_id,object,0,33,participant_or_group_identifier,0
1,study_version,object,0,1,form_or_backend_metadata,0
2,schema_version,object,0,1,form_or_backend_metadata,0
3,stimulus_configuration_version,object,0,1,form_or_backend_metadata,0
4,source_version,object,0,1,form_or_backend_metadata,0
5,submission_status,object,0,1,form_or_backend_metadata,0
6,study_group,object,0,2,participant_or_group_identifier,0
7,group_id,object,0,2,participant_or_group_identifier,0
8,started_at,datetime64[ns],1,32,timestamp,0
9,completed_at,datetime64[ns],0,33,timestamp,0
10,duration_seconds,float64,1,31,form_or_backend_metadata,0
11,trial_count,int64,0,1,completion_count,0
12,version_count,int64,0,1,completion_count,0
13,rating_count,int64,0,1,completion_count,0
14,comment_count,int64,0,1,completion_count,0
15,consent_confirmed,bool,0,1,form_or_backend_metadata,0
16,consent_json,object,0,33,participant_metadata_json,0
17,listening_setup_json,object,0,33,participant_metadata_json,0
18,pre_study_json,object,0,33,participant_metadata_json,0
19,practice_json,object,0,33,structured_json,0
20,demographics_json,object,0,32,participant_metadata_json,0
21,post_task_json,object,0,29,participant_metadata_json,0
22,assigned_song_ids_json,object,0,2,structured_json,0
23,scenario_order_json,object,0,6,trial_randomisation_or_response_json,0
24,episode_order_json,object,0,6,trial_randomisation_or_response_json,0
25,song_order_json,object,0,29,trial_randomisation_or_response_json,0
26,trial_order_json,object,0,33,trial_randomisation_or_response_json,0
27,mix_mapping_json,object,0,33,trial_randomisation_or_response_json,0
28,presentation_order_json,object,0,29,trial_randomisation_or_response_json,0
29,trial_records_json,object,0,33,trial_randomisation_or_response_json,0
30,responses_json,object,0,33,trial_randomisation_or_response_json,0
31,derived_preferences_json,object,0,33,structured_json,0
32,timing_json,object,0,33,structured_json,0
33,device_browser_json,object,0,25,structured_json,0
34,client_validation_json,object,0,1,structured_json,0
35,final_payload_json,object,0,33,structured_json,33
36,ip,object,0,27,backend_or_browser_metadata,0
37,user_agent,object,0,16,backend_or_browser_metadata,0
38,referrer,object,0,1,backend_or_browser_metadata,0
39,created_at,datetime64[ns],0,33,timestamp,0

## Submission and Participant Completeness Audit

In [5]:
outputs["exclusion_log"][[
    "participant_id", "group", "n_episodes_completed", "n_song_episode_trials_completed",
    "n_ratings", "n_comments", "missing_ratings", "missing_comments",
    "duplicated_trial_rating_combinations", "duplicate_classification",
    "complete_submission", "include_recommended", "requires_manual_review", "exclusion_reason"
]]

,participant_id,group,n_episodes_completed,n_song_episode_trials_completed,n_ratings,n_comments,missing_ratings,missing_comments,duplicated_trial_rating_combinations,duplicate_classification,complete_submission,include_recommended,requires_manual_review,exclusion_reason
0,P033,group_02,3,6,30,30,0,0,0,no duplicate concern,True,True,False,
1,P032,group_02,3,6,30,30,0,0,0,no duplicate concern,True,True,False,
2,P031,group_01,3,6,30,30,0,0,0,no duplicate concern,True,True,False,
3,P030,group_02,3,6,30,30,0,0,0,no duplicate concern,True,True,False,
4,P029,group_02,3,6,30,30,0,0,0,no duplicate concern,True,True,False,
5,P028,group_01,3,6,30,30,0,0,0,no duplicate concern,True,True,False,
6,P027,group_02,3,6,30,30,0,0,0,no duplicate concern,True,True,False,
7,P026,group_02,3,6,30,30,0,0,0,no duplicate concern,True,True,False,
8,P025,group_01,3,6,30,30,0,0,0,no duplicate concern,True,True,False,
9,P024,group_01,3,6,30,30,0,0,0,no duplicate concern,True,True,False,
10,P023,group_02,3,6,30,30,0,0,0,no duplicate concern,True,True,False,
11,P022,group_01,3,6,30,30,0,0,0,no duplicate concern,True,True,False,
12,P021,group_01,3,6,30,30,0,0,0,no duplicate concern,True,True,False,
13,P020,group_02,3,6,30,30,0,0,0,no duplicate concern,True,True,False,
14,P019,group_02,3,6,30,30,0,0,0,no duplicate concern,True,True,False,
15,P018,group_02,3,6,30,30,0,0,0,no duplicate concern,True,True,False,
16,P017,group_02,3,6,30,30,0,0,0,no duplicate concern,True,True,False,
17,P016,group_01,3,6,30,30,0,0,0,no duplicate concern,True,True,False,
18,P015,group_01,3,6,30,30,0,0,0,no duplicate concern,True,True,False,
19,P014,group_01,3,6,30,30,0,0,0,no duplicate concern,True,True,False,
20,P013,group_02,3,6,30,30,0,0,0,no duplicate concern,True,True,False,
21,P012,group_01,3,6,30,30,0,0,0,no duplicate concern,True,True,False,
22,P011,group_02,3,6,30,30,0,0,0,no duplicate concern,True,True,False,
23,P010,group_01,3,6,30,30,0,0,0,no duplicate concern,True,True,False,
24,P009,group_02,3,6,30,30,0,0,0,no duplicate concern,True,True,False,
25,P008,group_01,3,6,30,30,0,0,0,no duplicate concern,True,True,False,
26,P007,group_02,3,6,30,30,0,0,0,no duplicate concern,True,True,False,
27,P006,group_01,3,6,30,30,0,0,0,no duplicate concern,True,True,False,
28,P005,group_02,3,6,30,30,0,0,0,no duplicate concern,True,True,False,
29,P004,group_01,3,6,30,30,0,0,0,no duplicate concern,True,True,False,
30,P003,group_01,3,6,30,30,0,0,0,no duplicate concern,True,True,False,
31,P002,group_01,3,6,30,30,0,0,0,no duplicate concern,True,True,False,
32,P001,group_01,3,6,30,30,0,0,0,no duplicate concern,True,True,False,

## Rating, Comment, Randomisation, and Feature Validation

In [6]:
validation

                                           check  passed details
0                          raw_workbook_has_rows    True
1                    one_wide_row_per_submission    True
2                               all_groups_valid    True
3              all_group_song_combinations_valid    True
4                             all_episodes_valid    True
5                             all_songs_expected    True
6                           all_stimuli_expected    True
7       all_randomisation_mappings_reconstructed    True
8                             no_invalid_ratings    True
9             no_missing_comments_on_rating_rows    True
10        all_trials_have_five_unique_candidates    True
11    complete_participants_have_expected_trials    True
12  complete_participants_have_expected_episodes    True
13                           all_features_mapped    True
14           no_accidental_duplicate_rating_rows    True
15   exclusion_log_accounts_for_every_submission    True

## Derived Trial Preferences and Ties

In [7]:
outputs["trial_preferences"].head(), outputs["ties"].head(), outputs["summary"][["participant_song_episode_trials", "trials_with_rating_ties", "trial_tie_proportion"]]

(  participant_id     group          song_id episode        trial_id  \
 0           P001  group_01  id_like_to_know   EDR-1  P001__trial_06
 1           P001  group_01  id_like_to_know   EDR-2  P001__trial_03
 2           P001  group_01  id_like_to_know    FM-1  P001__trial_02
 3           P001  group_01          lead_me   EDR-1  P001__trial_05
 4           P001  group_01          lead_me   EDR-2  P001__trial_04

    trial_index  candidate_count  unique_candidate_count  rating_count  \
 0            6                5                       5             5
 1            3                5                       5             5
 2            2                5                       5             5
 3            5                5                       5             5
 4            4                5                       5             5

    comment_count  distinct_comment_count  max_rating  n_tied_winners  \
 0              5                       1          75               1
 1              5                       1          82               1
 2              5                       1          80               1
 3              5                       1          72               1
 4              5                       1          77               1

    tie_flag  preferred_mix_id   preferred_stimulus_id  \
 0     False  mix_9ffcd672af17  id_like_to_know_pxl_s1
 1     False  mix_6f8b655d7999  id_like_to_know_pxl_s2
 2     False  mix_9ffcd672af17  id_like_to_know_pxl_s1
 3     False  mix_f1f7973e5bac            lead_me_du_d
 4     False  mix_c7d9a071ba25          lead_me_pxl_l4

   preferred_presentation_label  expected_five_candidates  comments_present
 0                            D                      True              True
 1                            B                      True              True
 2                            E                      True              True
 3                            C                      True              True
 4                            E                      True              True  ,
   participant_id     group          song_id episode        trial_id  \
 0           P010  group_01  id_like_to_know   EDR-2  P010__trial_06
 1           P010  group_01  id_like_to_know   EDR-2  P010__trial_06
 2           P010  group_01  id_like_to_know   EDR-2  P010__trial_06
 3           P010  group_01  id_like_to_know   EDR-2  P010__trial_06
 4           P010  group_01  id_like_to_know   EDR-2  P010__trial_06

   presentation_label            mix_id             stimulus_id  rating
 0                  A  mix_82d60d7c7fc5  id_like_to_know_pxl_s5     100
 1                  B  mix_9ffcd672af17  id_like_to_know_pxl_s1     100
 2                  C  mix_6f8b655d7999  id_like_to_know_pxl_s2     100
 3                  D  mix_b393d3919c78  id_like_to_know_pxl_s7     100
 4                  E  mix_65f41f41d3ab  id_like_to_know_pxl_s3     100  ,
    participant_song_episode_trials  trials_with_rating_ties  \
 0                              198                       16

    trial_tie_proportion
 0              0.080808  )

## Participant Metadata Audit

In [8]:
outputs["metadata_audit"]

,metadata_variable,raw_representation,count,missing_count,unique_values,proposed_analysis_representation
0,age_range,25_34,24,0,5,preserve as collected; trimmed whitespace only
1,age_range,18_24,6,0,5,preserve as collected; trimmed whitespace only
2,age_range,35_44,1,0,5,preserve as collected; trimmed whitespace only
3,age_range,45_54,1,0,5,preserve as collected; trimmed whitespace only
4,age_range,55_64,1,0,5,preserve as collected; trimmed whitespace only
5,gender,man,17,1,3,preserve as collected; trimmed whitespace only
6,gender,woman,15,1,3,preserve as collected; trimmed whitespace only
7,gender,<missing>,1,1,3,preserve as collected; trimmed whitespace only
8,cultural_influence_country,Mexico,4,0,27,preserve as collected; trimmed whitespace only
9,cultural_influence_country,Japan,2,0,27,preserve as collected; trimmed whitespace only
10,cultural_influence_country,India,2,0,27,preserve as collected; trimmed whitespace only
11,cultural_influence_country,UK,2,0,27,preserve as collected; trimmed whitespace only
12,cultural_influence_country,"Greece, UK",1,0,27,preserve as collected; trimmed whitespace only
13,cultural_influence_country,"USA, UK",1,0,27,preserve as collected; trimmed whitespace only
14,cultural_influence_country,"Mexico, USA",1,0,27,preserve as collected; trimmed whitespace only
15,cultural_influence_country,"India, USA, UK",1,0,27,preserve as collected; trimmed whitespace only
16,cultural_influence_country,"Italy, UK",1,0,27,preserve as collected; trimmed whitespace only
17,cultural_influence_country,"India, UK",1,0,27,preserve as collected; trimmed whitespace only
18,cultural_influence_country,"Japan. (and British Rock, American Rock)",1,0,27,preserve as collected; trimmed whitespace only
19,cultural_influence_country,Sería Estados Unidos y países de Europa y un p...,1,0,27,preserve as collected; trimmed whitespace only
20,cultural_influence_country,"Mexico, UK, South Korea",1,0,27,preserve as collected; trimmed whitespace only
21,cultural_influence_country,korea,1,0,27,preserve as collected; trimmed whitespace only
22,cultural_influence_country,"Mexico, USA, UK",1,0,27,preserve as collected; trimmed whitespace only
23,cultural_influence_country,China、Japan、USA,1,0,27,preserve as collected; trimmed whitespace only
24,cultural_influence_country,Korea,1,0,27,preserve as collected; trimmed whitespace only
25,cultural_influence_country,USA,1,0,27,preserve as collected; trimmed whitespace only
26,cultural_influence_country,latin,1,0,27,preserve as collected; trimmed whitespace only
27,cultural_influence_country,uk,1,0,27,preserve as collected; trimmed whitespace only
28,cultural_influence_country,"Taiwan, with a very strong influence from US h...",1,0,27,preserve as collected; trimmed whitespace only
29,cultural_influence_country,United states,1,0,27,preserve as collected; trimmed whitespace only
30,cultural_influence_country,United States,1,0,27,preserve as collected; trimmed whitespace only
31,cultural_influence_country,English-spoken Rock and Pop music. Mexican Mus...,1,0,27,preserve as collected; trimmed whitespace only
32,cultural_influence_country,South korea,1,0,27,preserve as collected; trimmed whitespace only
33,cultural_influence_country,"Mexico, Puerto Rico, USA",1,0,27,preserve as collected; trimmed whitespace only
34,cultural_influence_country,"America, i like slow indie music",1,0,27,preserve as collected; trimmed whitespace only
35,music_listening_habits,daily,29,0,2,preserve as collected; trimmed whitespace only
36,music_listening_habits,several_times_week,4,0,2,preserve as collected; trimmed whitespace only
37,music_production_or_audio_engineering_experience,none,18,0,4,preserve as collected; trimmed whitespace only
38,music_production_or_audio_engineering_experience,basic,10,0,4,preserve as collected; trimmed whitespace only
39,music_production_or_audio_engineering_experience,intermediate,3,0,4,preserve as collected; trimmed whitespace only
40,music_production_or_audio_engineering_experience,advanced,2,0,4,preserve as collected; trimmed whitespace only
41,hearing_difficulty,no,33,0,1,preserve as collected; trimmed whitespace only
42,scenario_immersion,4,14,0,5,preserve as collected; trimmed whitespace only
43,scenario_immersion,5,12,0,5,preserve as collected; trimmed whitespace only
44,scenario_immersion,3,5,0,5,preserve as collected; trimmed whitespace only
45,scenario_immersion,2,1,0,5,preserve as collected; trimmed whitespace only
46,scenario_immersion,1,1,0,5,preserve as collected; trimmed whitespace only
47,task_difficulty,2,11,0,5,preserve as collected; trimmed whitespace only
48,task_difficulty,4,8,0,5,preserve as collected; trimmed whitespace only
49,task_difficulty,3,8,0,5,preserve as collected; trimmed whitespace only
50,task_difficulty,1,5,0,5,preserve as collected; trimmed whitespace only
51,task_difficulty,5,1,0,5,preserve as collected; trimmed whitespace only
52,prior_excerpt_familiarity,no,31,0,2,preserve as collected; trimmed whitespace only
53,prior_excerpt_familiarity,yes,2,0,2,preserve as collected; trimmed whitespace only
54,headphones_or_earphones_used,earphones,17,0,3,preserve as collected; trimmed whitespace only
55,headphones_or_earphones_used,headphones,9,0,3,preserve as collected; trimmed whitespace only
56,headphones_or_earphones_used,phone_or_laptop_speakers,7,0,3,preserve as collected; trimmed whitespace only
57,completion_location_or_environment,quiet_private_space,31,0,2,preserve as collected; trimmed whitespace only
58,completion_location_or_environment,shared_indoor_space,2,0,2,preserve as collected; trimmed whitespace only

## Canonical Outputs and Final Gate

In [9]:
print(summary.loc[0, "final_gate"])
for label, path in manifest["outputs"].items():
    print(f"{label}: {PROJECT_ROOT / path}")

REAL DATA READY FOR STATISTICAL MODELLING
ratings: C:\Users\oscar\Documents\7. QMUL UNIVERSITY\1. Master Program\3. MSc Project\intent2control-dissertation\statistical-baseline\data\real\real_ratings_clean.csv
participants: C:\Users\oscar\Documents\7. QMUL UNIVERSITY\1. Master Program\3. MSc Project\intent2control-dissertation\statistical-baseline\data\real\real_participants_clean.csv
trial_preferences: C:\Users\oscar\Documents\7. QMUL UNIVERSITY\1. Master Program\3. MSc Project\intent2control-dissertation\statistical-baseline\data\real\real_trial_preferences.csv
ties: C:\Users\oscar\Documents\7. QMUL UNIVERSITY\1. Master Program\3. MSc Project\intent2control-dissertation\statistical-baseline\data\real\real_trial_ties_long.csv
submission_audit: C:\Users\oscar\Documents\7. QMUL UNIVERSITY\1. Master Program\3. MSc Project\intent2control-dissertation\statistical-baseline\data\real\real_submission_audit.csv
exclusion_log: C:\Users\oscar\Documents\7. QMUL UNIVERSITY\1. Master Program\3. MSc Project\intent2control-dissertation\statistical-baseline\data\real\real_exclusion_log.csv
validation: C:\Users\oscar\Documents\7. QMUL UNIVERSITY\1. Master Program\3. MSc Project\intent2control-dissertation\statistical-baseline\data\real\real_data_validation.csv
summary: C:\Users\oscar\Documents\7. QMUL UNIVERSITY\1. Master Program\3. MSc Project\intent2control-dissertation\statistical-baseline\data\real\real_data_summary.csv
schema_audit: C:\Users\oscar\Documents\7. QMUL UNIVERSITY\1. Master Program\3. MSc Project\intent2control-dissertation\statistical-baseline\data\real\real_schema_audit.csv
metadata_audit: C:\Users\oscar\Documents\7. QMUL UNIVERSITY\1. Master Program\3. MSc Project\intent2control-dissertation\statistical-baseline\data\real\real_participant_metadata_audit.csv
downstream_stale: C:\Users\oscar\Documents\7. QMUL UNIVERSITY\1. Master Program\3. MSc Project\intent2control-dissertation\statistical-baseline\data\real\real_downstream_stale_outputs.csv
manifest: C:\Users\oscar\Documents\7. QMUL UNIVERSITY\1. Master Program\3. MSc Project\intent2control-dissertation\statistical-baseline\data\real\real_cleaning_manifest.json