# Phase 3 Real Stimulus-Based Bayesian Multilevel Model

This notebook fits the final pre-specified empirical stimulus model on the cleaned real participant dataset.

Primary model:

`rating ~ episode + group + (1 | participant_id) + (1 | stimulus_id)`

The model uses a Gaussian likelihood in native 0-100 rating units, participant and stimulus random intercepts, and fixed effects for episode and group. The raw data and cleaning decisions are not modified. No acoustic predictors, interactions, random slopes, song random effects, or participant metadata predictors are added here.

In [1]:
from pathlib import Path
import sys

PROJECT_ROOT = Path.cwd().resolve()
if PROJECT_ROOT.name == "notebooks":
    PROJECT_ROOT = PROJECT_ROOT.parents[1]
elif not (PROJECT_ROOT / "statistical-baseline").exists():
    PROJECT_ROOT = next(path for path in [Path.cwd().resolve(), *Path.cwd().resolve().parents] if (path / "statistical-baseline").exists())

sys.path.insert(0, str(PROJECT_ROOT / "statistical-baseline" / "src"))

from statistical_baseline.real_stimulus_model import (
    FINAL_FORMULA,
    INTERCEPT_FORMULA,
    OUTPUT_DIR,
    RATINGS_PATH,
    run_real_stimulus_model,
)

RATINGS_PATH, OUTPUT_DIR, INTERCEPT_FORMULA, FINAL_FORMULA

WARNING (pytensor.configdefaults): g++ not available, if using conda: `conda install gxx`

WARNING (pytensor.configdefaults): g++ not detected!  PyTensor will be unable to compile C-implementations and will default to Python. Performance may be severely degraded. To remove this warning, set PyTensor flags cxx to an empty string.

(WindowsPath('C:/Users/oscar/Documents/7. QMUL UNIVERSITY/1. Master Program/3. MSc Project/intent2control-dissertation/statistical-baseline/data/real/real_ratings_clean.csv'),
 WindowsPath('C:/Users/oscar/Documents/7. QMUL UNIVERSITY/1. Master Program/3. MSc Project/intent2control-dissertation/statistical-baseline/outputs/real_stimulus_model'),
 'rating ~ 1 + (1 | participant_id) + (1 | stimulus_id)',
 'rating ~ episode + group + (1 | participant_id) + (1 | stimulus_id)')

## Execute Locked Empirical Model Pipeline

Sampling settings are 4 chains, 1000 tuning draws, 1000 posterior draws, `target_accept=0.95`, deterministic seed, and nutpie where available. If nutpie is unavailable, the code records the PyMC fallback reason rather than changing the scientific model.

In [2]:
outputs = run_real_stimulus_model()
outputs.keys()

C:\Users\oscar\miniconda3\lib\site-packages\pymc\sampling\mcmc.py:328: UserWarning: `idata_kwargs` are currently ignored by the nutpie sampler
  warnings.warn(

C:\Users\oscar\miniconda3\lib\site-packages\pymc\sampling\mcmc.py:328: UserWarning: `idata_kwargs` are currently ignored by the nutpie sampler
  warnings.warn(

dict_keys(['summary', 'validation', 'descriptive', 'intercept_idata', 'final_idata', 'runtimes', 'diagnostics', 'variance', 'icc', 'fixed', 'episode_means', 'episode_contrasts', 'ppc', 'expected', 'winners', 'winner_validation', 'observed_preferences', 'findings_text'])

## Modelling Dataset Validation

In [3]:
outputs["validation"]

,check,passed,actual_value
0,final_analysable_n_30,True,30
1,group_01_n_16,True,16
2,group_02_n_14,True,14
3,rating_observations_900,True,900
4,stimuli_20,True,20
5,songs_4,True,4
6,episodes_3,True,3
7,ratings_per_participant_30,True,"{""count"": 30.0, ""mean"": 30.0, ""std"": 0.0, ""min..."
8,no_missing_outcome,True,0
9,no_invalid_ratings,True,0
10,no_missing_identifiers,True,0

## Real Descriptive Summaries

In [4]:
outputs["descriptive"].head(40)

,summary_type,level,n,mean,median,sd,min,max
0,overall,all,900,53.217778,55.00,32.134093,0.000000,100.000000
1,episode,EDR-1,300,54.580000,58.00,31.261925,0.000000,100.000000
2,episode,EDR-2,300,56.763333,62.50,32.504808,0.000000,100.000000
3,episode,FM-1,300,48.310000,50.00,32.127785,0.000000,100.000000
4,group,group_01,480,49.939583,50.00,30.648974,0.000000,100.000000
5,group,group_02,420,56.964286,68.00,33.395742,0.000000,100.000000
6,stimulus,id_like_to_know_pxl_s1,48,49.270833,52.50,33.639984,0.000000,100.000000
7,stimulus,id_like_to_know_pxl_s2,48,60.916667,60.50,26.298478,0.000000,100.000000
8,stimulus,id_like_to_know_pxl_s3,48,55.541667,59.00,35.077397,0.000000,100.000000
9,stimulus,id_like_to_know_pxl_s5,48,43.500000,46.50,26.075178,0.000000,100.000000
10,stimulus,id_like_to_know_pxl_s7,48,50.791667,55.00,27.279451,0.000000,100.000000
11,stimulus,in_the_meantime_du_h,42,74.238095,76.00,21.851840,0.000000,100.000000
12,stimulus,in_the_meantime_du_i,42,60.714286,74.50,31.062711,0.000000,100.000000
13,stimulus,in_the_meantime_du_k,42,23.690476,7.50,29.622411,0.000000,99.000000
14,stimulus,in_the_meantime_qut_b,42,47.142857,49.00,34.362892,0.000000,100.000000
15,stimulus,in_the_meantime_qut_pro,42,59.904762,64.00,29.777066,0.000000,100.000000
16,stimulus,lead_me_du_d,48,52.208333,50.00,29.282162,0.000000,100.000000
17,stimulus,lead_me_du_e,48,34.937500,32.00,30.593704,0.000000,93.000000
18,stimulus,lead_me_mcg_pro2,48,59.375000,61.00,28.391357,0.000000,100.000000
19,stimulus,lead_me_pxl_l1,48,45.458333,42.50,32.286588,0.000000,100.000000
20,stimulus,lead_me_pxl_l4,48,47.395833,47.50,30.033130,0.000000,100.000000
21,stimulus,pouring_room_mcg_pro1,42,74.809524,77.00,23.895339,0.000000,100.000000
22,stimulus,pouring_room_mcg_r,42,77.404762,79.00,22.329090,0.000000,100.000000
23,stimulus,pouring_room_mcg_t,42,34.690476,25.50,32.885231,0.000000,100.000000
24,stimulus,pouring_room_mcg_v,42,59.190476,70.00,32.538336,0.000000,100.000000
25,stimulus,pouring_room_mcg_x,42,57.857143,57.00,31.148403,0.000000,100.000000
26,participant_mean_distribution,participant_means,30,53.217778,53.05,12.498560,15.333333,84.033333
27,rating_distribution_bin,0-20,191,NaN,NaN,NaN,NaN,NaN
28,rating_distribution_bin,21-40,133,NaN,NaN,NaN,NaN,NaN
29,rating_distribution_bin,41-60,157,NaN,NaN,NaN,NaN,NaN
30,rating_distribution_bin,61-80,203,NaN,NaN,NaN,NaN,NaN
31,rating_distribution_bin,81-100,216,NaN,NaN,NaN,NaN,NaN
32,observed_preference_trials,all,180,NaN,NaN,NaN,NaN,NaN

## Empirical ICCs and Variance Components

Participant ICC is the proportion of residual rating variance associated with stable between-listener differences. Stimulus ICC is the proportion associated with differences among the 20 mix stimuli.

In [5]:
outputs["variance"], outputs["icc"]

(                     term    mean     sd   hdi_3  hdi_97   mcse  mcse_sd  \
 0  1|participant_id_sigma  11.551  1.908   8.198  15.208  0.060    0.035
 1     1|stimulus_id_sigma  13.830  2.708   9.029  18.839  0.110    0.074
 2                   sigma  27.661  0.678  26.406  28.918  0.009    0.012

    ess_bulk  ess_tail  r_hat
 0    1001.0    1788.0    1.0
 1     629.0     968.0    1.0
 2    5473.0    2824.0    1.0  ,
                    term     mean      sd    hdi_3   hdi_97   mcse  mcse_sd  \
 0  participant_variance  137.074  46.170   64.248  227.074  1.431    1.037
 1     stimulus_variance  198.613  81.875   79.741  351.900  3.296    3.149
 2     residual_variance  765.579  37.611  697.277  836.241  0.516    0.682
 3       participant_ICC    0.124   0.037    0.061    0.195  0.001    0.001
 4          stimulus_ICC    0.177   0.057    0.084    0.287  0.002    0.002
 5        residual_share    0.699   0.056    0.590    0.798  0.002    0.001

    ess_bulk  ess_tail  r_hat
 0    1001.0    1788.0    1.0
 1     629.0     968.0    1.0
 2    5473.0    2824.0    1.0
 3     893.0    1748.0    1.0
 4     583.0     941.0    1.0
 5     806.0    1132.0    1.0  )

## Fixed Effects, Episode Means, and Episode Contrasts

In [6]:
outputs["fixed"], outputs["episode_means"], outputs["episode_contrasts"]

(              term    mean     sd   hdi_3  hdi_97   mcse  mcse_sd  ess_bulk  \
 0        Intercept  51.388  5.720  40.503  61.826  0.267    0.189     463.0
 1   episode[EDR-2]   2.147  2.269  -2.119   6.462  0.043    0.030    2769.0
 2    episode[FM-1]  -6.292  2.200 -10.390  -2.144  0.041    0.029    2874.0
 3  group[group_02]   6.868  7.735  -6.425  22.576  0.349    0.198     492.0

    ess_tail  r_hat
 0     557.0   1.01
 1    2797.0   1.00
 2    2828.0   1.00
 3     921.0   1.01  ,
   summary_type  level       mean     median        sd      hdi_3     hdi_97  \
 0      episode  EDR-1  54.593521  54.510070  4.310200  46.533787  62.849524
 1      episode  EDR-2  56.740610  56.709797  4.330556  48.434418  64.839720
 2      episode   FM-1  48.301966  48.267481  4.329634  40.013428  56.355321

    probability_above_zero  probability_below_zero
 0                     1.0                     0.0
 1                     1.0                     0.0
 2                     1.0                     0.0  ,
        summary_type              level      mean    median        sd  \
 0  episode_contrast  EDR-2 minus EDR-1  2.147089  2.170674  2.269433
 1  episode_contrast   FM-1 minus EDR-1 -6.291554 -6.276671  2.199806
 2  episode_contrast   FM-1 minus EDR-2 -8.438644 -8.456623  2.266710

        hdi_3    hdi_97  probability_above_zero  probability_below_zero
 0  -2.119181  6.462408                 0.82175                 0.17825
 1 -10.389620 -2.144048                 0.00200                 0.99800
 2 -12.507464 -4.097231                 0.00000                 1.00000  )

## Convergence Diagnostics

In [7]:
outputs["diagnostics"]

,model_name,divergences,max_rhat,min_bulk_ess,min_tail_ess,max_tree_depth,tree_depth_warnings,energy_warnings,runtime_seconds,sampler
0,intercept_only,0,1.01,463.0,695.0,NaN,0,0,24.531825,bambi_pymc_nutpie
1,final_stimulus,0,1.01,463.0,557.0,NaN,0,0,20.077196,bambi_pymc_nutpie

## Posterior Predictive Checks

Posterior predictive samples are not clipped; outside-range rates diagnose whether the Gaussian likelihood is materially strained by the bounded 0-100 scale.

In [8]:
outputs["ppc"]

                                metric      value
0                        observed_mean  53.217778
1                          observed_sd  32.134093
2       posterior_predictive_mean_mean  53.218572
3         posterior_predictive_sd_mean  32.285727
4         posterior_predictive_below_0   0.050232
5       posterior_predictive_above_100   0.073403
6   posterior_predictive_outside_0_100   0.123635
7          observed_episode_mean_EDR-1  54.580000
8               ppc_episode_mean_EDR-1  54.622556
9          observed_episode_mean_EDR-2  56.763333
10              ppc_episode_mean_EDR-2  56.726804
11          observed_episode_mean_FM-1  48.310000
12               ppc_episode_mean_FM-1  48.306355
13        observed_group_mean_group_01  49.939583
14             ppc_group_mean_group_01  49.927782
15        observed_group_mean_group_02  56.964286
16             ppc_group_mean_group_02  56.979474
17           observed_stimulus_mean_sd  13.668797
18                ppc_stimulus_mean_sd  12.487918

## Posterior Expected Ratings and Highest-Rated Mix Probabilities

Posterior highest-rated-mix probabilities compare the five valid stimuli within each `song_id x episode` combination for every posterior expected-rating draw. Exact draw-level ties receive fractional credit.

Because the model is additive and contains no Episode x Stimulus interaction, stimulus differences are assumed constant across episodes on the model scale. The model can produce episode-specific expected ratings through overall episode shifts, but it should not be interpreted as evidence for context-dependent stimulus reversals.

In [9]:
outputs["expected"].head(), outputs["winners"].head(20), outputs["winner_validation"]

(      group episode          song_id             stimulus_id  \
 0  group_01   EDR-1  id_like_to_know  id_like_to_know_pxl_s1
 1  group_01   EDR-1  id_like_to_know  id_like_to_know_pxl_s2
 2  group_01   EDR-1  id_like_to_know  id_like_to_know_pxl_s3
 3  group_01   EDR-1  id_like_to_know  id_like_to_know_pxl_s5
 4  group_01   EDR-1  id_like_to_know  id_like_to_know_pxl_s7

              mix_id       mean     median        sd      hdi_3     hdi_97  \
 0  mix_9ffcd672af17  50.781493  50.692609  5.024594  41.260777  59.898847
 1  mix_6f8b655d7999  61.416668  61.411965  4.872764  52.402837  70.804840
 2  mix_65f41f41d3ab  56.609088  56.627627  4.867825  47.438054  65.619209
 3  mix_82d60d7c7fc5  45.454261  45.352729  4.894738  36.227383  54.648943
 4  mix_b393d3919c78  52.183252  52.212213  4.820300  42.890505  61.212225

    probability_above_zero  probability_below_zero
 0                     1.0                     0.0
 1                     1.0                     0.0
 2                     1.0                     0.0
 3                     1.0                     0.0
 4                     1.0                     0.0  ,
             song_id     group episode              stimulus_id  \
 0   id_like_to_know  group_01   EDR-1   id_like_to_know_pxl_s1
 1   id_like_to_know  group_01   EDR-1   id_like_to_know_pxl_s2
 2   id_like_to_know  group_01   EDR-1   id_like_to_know_pxl_s3
 3   id_like_to_know  group_01   EDR-1   id_like_to_know_pxl_s5
 4   id_like_to_know  group_01   EDR-1   id_like_to_know_pxl_s7
 5   id_like_to_know  group_01   EDR-2   id_like_to_know_pxl_s1
 6   id_like_to_know  group_01   EDR-2   id_like_to_know_pxl_s2
 7   id_like_to_know  group_01   EDR-2   id_like_to_know_pxl_s3
 8   id_like_to_know  group_01   EDR-2   id_like_to_know_pxl_s5
 9   id_like_to_know  group_01   EDR-2   id_like_to_know_pxl_s7
 10  id_like_to_know  group_01    FM-1   id_like_to_know_pxl_s1
 11  id_like_to_know  group_01    FM-1   id_like_to_know_pxl_s2
 12  id_like_to_know  group_01    FM-1   id_like_to_know_pxl_s3
 13  id_like_to_know  group_01    FM-1   id_like_to_know_pxl_s5
 14  id_like_to_know  group_01    FM-1   id_like_to_know_pxl_s7
 15  in_the_meantime  group_02   EDR-1     in_the_meantime_du_h
 16  in_the_meantime  group_02   EDR-1     in_the_meantime_du_i
 17  in_the_meantime  group_02   EDR-1     in_the_meantime_du_k
 18  in_the_meantime  group_02   EDR-1    in_the_meantime_qut_b
 19  in_the_meantime  group_02   EDR-1  in_the_meantime_qut_pro

               mix_id  posterior_mean_expected_rating      hdi_3     hdi_97  \
 0   mix_9ffcd672af17                       50.781493  41.260777  59.898847
 1   mix_6f8b655d7999                       61.416668  52.402837  70.804840
 2   mix_65f41f41d3ab                       56.609088  47.438054  65.619209
 3   mix_82d60d7c7fc5                       45.454261  36.227383  54.648943
 4   mix_b393d3919c78                       52.183252  42.890505  61.212225
 5   mix_9ffcd672af17                       52.928582  43.588632  62.229628
 6   mix_6f8b655d7999                       63.563757  54.675571  73.160098
 7   mix_65f41f41d3ab                       58.756177  49.099433  67.506682
 8   mix_82d60d7c7fc5                       47.601350  38.135157  56.924439
 9   mix_b393d3919c78                       54.330342  45.501554  63.633686
 10  mix_9ffcd672af17                       44.489938  35.454057  54.111864
 11  mix_6f8b655d7999                       55.125113  45.978700  64.386431
 12  mix_65f41f41d3ab                       50.317533  41.215073  59.702494
 13  mix_82d60d7c7fc5                       39.162707  29.209529  47.864462
 14  mix_b393d3919c78                       45.891698  36.673320  55.026866
 15  mix_302f0efe8a80                       73.797956  64.187749  84.410022
 16  mix_9baa86357fd4                       61.656052  51.391481  71.225841
 17  mix_56e65a3ce054                       28.029487  17.645309  38.267042
 18  mix_c7bdcba64775                       49.291160  39.342316  59.387546
 19  mix_cdaef40f2b94                       60.797153  50.478572  71.082726

     posterior_probability_highest  is_final_predicted_winner  \
 0                         0.01200                      False
 1                         0.78675                       True
 2                         0.18150                      False
 3                         0.00000                      False
 4                         0.01975                      False
 5                         0.01200                      False
 6                         0.78675                       True
 7                         0.18150                      False
 8                         0.00000                      False
 9                         0.01975                      False
 10                        0.01200                      False
 11                        0.78675                       True
 12                        0.18150                      False
 13                        0.00000                      False
 14                        0.01975                      False
 15                        0.97275                       True
 16                        0.01600                      False
 17                        0.00000                      False
 18                        0.00000                      False
 19                        0.01125                      False

     draw_level_tie_probability  final_probability_tie_flag
 0                          0.0                       False
 1                          0.0                       False
 2                          0.0                       False
 3                          0.0                       False
 4                          0.0                       False
 5                          0.0                       False
 6                          0.0                       False
 7                          0.0                       False
 8                          0.0                       False
 9                          0.0                       False
 10                         0.0                       False
 11                         0.0                       False
 12                         0.0                       False
 13                         0.0                       False
 14                         0.0                       False
 15                         0.0                       False
 16                         0.0                       False
 17                         0.0                       False
 18                         0.0                       False
 19                         0.0                       False  ,
             song_id episode  candidate_count  probability_sum  \
 0   id_like_to_know   EDR-1                5              1.0
 1   id_like_to_know   EDR-2                5              1.0
 2   id_like_to_know    FM-1                5              1.0
 3   in_the_meantime   EDR-1                5              1.0
 4   in_the_meantime   EDR-2                5              1.0
 5   in_the_meantime    FM-1                5              1.0
 6           lead_me   EDR-1                5              1.0
 7           lead_me   EDR-2                5              1.0
 8           lead_me    FM-1                5              1.0
 9      pouring_room   EDR-1                5              1.0
 10     pouring_room   EDR-2                5              1.0
 11     pouring_room    FM-1                5              1.0

     probabilities_between_0_and_1  n_final_winners  \
 0                            True                1
 1                            True                1
 2                            True                1
 3                            True                1
 4                            True                1
 5                            True                1
 6                            True                1
 7                            True                1
 8                            True                1
 9                            True                1
 10                           True                1
 11                           True                1

     draw_level_tie_probability  final_probability_tie_flag  validation_passed
 0                          0.0                       False               True
 1                          0.0                       False               True
 2                          0.0                       False               True
 3                          0.0                       False               True
 4                          0.0                       False               True
 5                          0.0                       False               True
 6                          0.0                       False               True
 7                          0.0                       False               True
 8                          0.0                       False               True
 9                          0.0                       False               True
 10                         0.0                       False               True
 11                         0.0                       False               True  )

## Observed Human Preference Summary

This table is an in-sample descriptive fit aid only. It is not out-of-sample predictive performance.

In [10]:
outputs["observed_preferences"].head(40)

,song_id,group,episode,stimulus_id,mix_id,observed_winner_credit,observed_winner_trials,tied_winner_rows,song_episode_trials,observed_winner_share_fractional_ties,comparison_scope
0,id_like_to_know,group_01,EDR-1,id_like_to_know_pxl_s1,mix_9ffcd672af17,6.000000,6,0,16,0.375000,in-sample descriptive fit only
2,id_like_to_know,group_01,EDR-1,id_like_to_know_pxl_s3,mix_65f41f41d3ab,5.000000,5,0,16,0.312500,in-sample descriptive fit only
3,id_like_to_know,group_01,EDR-1,id_like_to_know_pxl_s7,mix_b393d3919c78,3.000000,3,0,16,0.187500,in-sample descriptive fit only
1,id_like_to_know,group_01,EDR-1,id_like_to_know_pxl_s2,mix_6f8b655d7999,2.000000,2,0,16,0.125000,in-sample descriptive fit only
5,id_like_to_know,group_01,EDR-2,id_like_to_know_pxl_s2,mix_6f8b655d7999,5.700000,7,2,16,0.356250,in-sample descriptive fit only
6,id_like_to_know,group_01,EDR-2,id_like_to_know_pxl_s3,mix_65f41f41d3ab,4.700000,6,2,16,0.293750,in-sample descriptive fit only
4,id_like_to_know,group_01,EDR-2,id_like_to_know_pxl_s1,mix_9ffcd672af17,2.700000,4,2,16,0.168750,in-sample descriptive fit only
8,id_like_to_know,group_01,EDR-2,id_like_to_know_pxl_s7,mix_b393d3919c78,1.700000,3,2,16,0.106250,in-sample descriptive fit only
7,id_like_to_know,group_01,EDR-2,id_like_to_know_pxl_s5,mix_82d60d7c7fc5,1.200000,2,1,16,0.075000,in-sample descriptive fit only
11,id_like_to_know,group_01,FM-1,id_like_to_know_pxl_s3,mix_65f41f41d3ab,6.200000,7,1,16,0.387500,in-sample descriptive fit only
9,id_like_to_know,group_01,FM-1,id_like_to_know_pxl_s1,mix_9ffcd672af17,3.700000,5,2,16,0.231250,in-sample descriptive fit only
13,id_like_to_know,group_01,FM-1,id_like_to_know_pxl_s7,mix_b393d3919c78,3.200000,4,1,16,0.200000,in-sample descriptive fit only
10,id_like_to_know,group_01,FM-1,id_like_to_know_pxl_s2,mix_6f8b655d7999,1.700000,3,2,16,0.106250,in-sample descriptive fit only
12,id_like_to_know,group_01,FM-1,id_like_to_know_pxl_s5,mix_82d60d7c7fc5,1.200000,2,1,16,0.075000,in-sample descriptive fit only
18,in_the_meantime,group_02,EDR-1,in_the_meantime_qut_pro,mix_cdaef40f2b94,5.000000,5,0,14,0.357143,in-sample descriptive fit only
15,in_the_meantime,group_02,EDR-1,in_the_meantime_du_i,mix_9baa86357fd4,4.000000,4,0,14,0.285714,in-sample descriptive fit only
14,in_the_meantime,group_02,EDR-1,in_the_meantime_du_h,mix_302f0efe8a80,3.000000,3,0,14,0.214286,in-sample descriptive fit only
16,in_the_meantime,group_02,EDR-1,in_the_meantime_du_k,mix_56e65a3ce054,1.000000,1,0,14,0.071429,in-sample descriptive fit only
17,in_the_meantime,group_02,EDR-1,in_the_meantime_qut_b,mix_c7bdcba64775,1.000000,1,0,14,0.071429,in-sample descriptive fit only
19,in_the_meantime,group_02,EDR-2,in_the_meantime_du_h,mix_302f0efe8a80,5.000000,5,0,14,0.357143,in-sample descriptive fit only
22,in_the_meantime,group_02,EDR-2,in_the_meantime_qut_b,mix_c7bdcba64775,4.000000,4,0,14,0.285714,in-sample descriptive fit only
20,in_the_meantime,group_02,EDR-2,in_the_meantime_du_i,mix_9baa86357fd4,2.000000,2,0,14,0.142857,in-sample descriptive fit only
21,in_the_meantime,group_02,EDR-2,in_the_meantime_du_k,mix_56e65a3ce054,2.000000,2,0,14,0.142857,in-sample descriptive fit only
23,in_the_meantime,group_02,EDR-2,in_the_meantime_qut_pro,mix_cdaef40f2b94,1.000000,1,0,14,0.071429,in-sample descriptive fit only
24,in_the_meantime,group_02,FM-1,in_the_meantime_du_h,mix_302f0efe8a80,5.450000,7,2,14,0.389286,in-sample descriptive fit only
25,in_the_meantime,group_02,FM-1,in_the_meantime_du_i,mix_9baa86357fd4,3.450000,5,2,14,0.246429,in-sample descriptive fit only
28,in_the_meantime,group_02,FM-1,in_the_meantime_qut_pro,mix_cdaef40f2b94,3.450000,5,2,14,0.246429,in-sample descriptive fit only
26,in_the_meantime,group_02,FM-1,in_the_meantime_du_k,mix_56e65a3ce054,1.200000,2,1,14,0.085714,in-sample descriptive fit only
27,in_the_meantime,group_02,FM-1,in_the_meantime_qut_b,mix_c7bdcba64775,0.450000,2,2,14,0.032143,in-sample descriptive fit only
30,lead_me,group_01,EDR-1,lead_me_mcg_pro2,mix_d3e3580b6e30,6.000000,6,0,16,0.375000,in-sample descriptive fit only
29,lead_me,group_01,EDR-1,lead_me_du_d,mix_f1f7973e5bac,4.000000,4,0,16,0.250000,in-sample descriptive fit only
31,lead_me,group_01,EDR-1,lead_me_pxl_l1,mix_d5b28dfc8a93,3.000000,3,0,16,0.187500,in-sample descriptive fit only
32,lead_me,group_01,EDR-1,lead_me_pxl_l4,mix_c7d9a071ba25,3.000000,3,0,16,0.187500,in-sample descriptive fit only
35,lead_me,group_01,EDR-2,lead_me_mcg_pro2,mix_d3e3580b6e30,4.333333,5,1,16,0.270833,in-sample descriptive fit only
33,lead_me,group_01,EDR-2,lead_me_du_d,mix_f1f7973e5bac,4.000000,4,0,16,0.250000,in-sample descriptive fit only
36,lead_me,group_01,EDR-2,lead_me_pxl_l1,mix_d5b28dfc8a93,3.833333,5,2,16,0.239583,in-sample descriptive fit only
34,lead_me,group_01,EDR-2,lead_me_du_e,mix_271852ba8676,2.333333,3,1,16,0.145833,in-sample descriptive fit only
37,lead_me,group_01,EDR-2,lead_me_pxl_l4,mix_c7d9a071ba25,1.500000,2,1,16,0.093750,in-sample descriptive fit only
38,lead_me,group_01,FM-1,lead_me_du_d,mix_f1f7973e5bac,6.000000,6,0,16,0.375000,in-sample descriptive fit only
40,lead_me,group_01,FM-1,lead_me_mcg_pro2,mix_d3e3580b6e30,5.000000,5,0,16,0.312500,in-sample descriptive fit only

## RQ2 Relevance

RQ2 asks: "To what extent do mix preferences vary between listeners and within the same listener across listening contexts?"

The current stimulus model informs RQ2 through the empirical participant ICC, participant random-effect variance, episode fixed effects, stimulus variance, and descriptive preference distributions. However, because the primary model contains no participant-specific episode slopes and no Episode x Stimulus interactions, it does not fully parameterise every form of within-listener context-specific heterogeneity.

## Sample-Size Context

The planned preferred analysable sample was N=50. The achieved analysable sample is N=30. This does not invalidate the study, but it means posterior estimates may be less precise than anticipated in the design simulations. The sample-size design analysis is not rerun retroactively to make N=30 appear planned.

## Empirical Stimulus-Model Findings

In [11]:
print(outputs["findings_text"])
print("\nExport directory:", OUTPUT_DIR)

# Empirical Stimulus-Model Findings

The achieved analysable sample was N=30, with 16 participants in group_01 and 14 in group_02.
The empirical participant ICC posterior mean was 0.124 with 94% HDI [0.061, 0.195], representing the proportion of residual rating variance associated with stable between-listener differences.
The empirical stimulus ICC posterior mean was 0.177 with 94% HDI [0.084, 0.287], representing the proportion associated with differences among the 20 mix stimuli. The residual share posterior mean was 0.699.
Episode fixed effects are additive context shifts in native rating-point units, averaged across group and stimulus variability; they should be interpreted by magnitude, direction, and uncertainty rather than binary significance language.
The group coefficient is structurally linked to song allocation, so it represents a systematic difference between the two assigned song sets / study groups rather than an independent causal effect of group membership.
The final model diagnostics recorded 0 divergences, maximum R-hat 1.010, minimum bulk ESS 463.0, and minimum tail ESS 557.0.
The Gaussian posterior predictive outside-range proportion was 0.1236; samples were not clipped.
Posterior highest-rated-mix probabilities were computed draw by draw using posterior expected ratings, with fractional credit for exact draw-level ties.
Because the primary model has no Episode x Stimulus interaction or participant-specific episode slopes, it does not fully parameterise context-specific stimulus reversals or every form of within-listener heterogeneity.
Planned preferred analysable sample size was 50; achieved analysable N was 30, so posterior estimates may be less precise than anticipated in the design simulations.


Export directory: C:\Users\oscar\Documents\7. QMUL UNIVERSITY\1. Master Program\3. MSc Project\intent2control-dissertation\statistical-baseline\outputs\real_stimulus_model